export const INITIAL_STATE_DATA = {
  nodeDataArray: [
    {
      key: 0,
      layer: "start",
      value: "start",
      fill: "black",
      color: "white",
      loc: "0 0",
      category: "Start",
    },
    {
      key: 1,
      layer: "size",
      value: "s",
      text: "ขนาด\nเล็ก",
      fill: "Grey",
      color: "white",
      loc: "200 -150",
    },
    {
      key: 2,
      layer: "size",
      value: "l",
      text: "ขนาด\nใหญ่",
      fill: "Grey",
      color: "white",
      loc: "200 150",
    },
    {
      key: 3,
      layer: "topping1",
      value: "brownie",
      text: "บราวนี่",
      fill: "GoldenRod",
      color: "white",
      loc: "450 -320",
    },
    {
      key: 4,
      layer: "topping1",
      value: "banana",
      text: "กล้วย",
      fill: "GoldenRod",
      color: "white",
      loc: "450 -200",
    },
    {
      key: 5,
      layer: "topping1",
      value: "cereal",
      text: "คอนเฟรค",
      fill: "GoldenRod",
      color: "white",
      loc: "450 -80",
    },
    {
      key: 6,
      layer: "topping2",
      value: "brownie",
      text: "บราวนี่",
      fill: "GoldenRod",
      color: "white",
      loc: "450 80",
    },
    {
      key: 7,
      layer: "topping2",
      value: "banana",
      text: "กล้วย",
      fill: "GoldenRod",
      color: "white",
      loc: "450 200",
    },
    {
      key: 8,
      layer: "topping2",
      value: "cereal",
      text: "คอนเฟรค",
      fill: "GoldenRod",
      color: "white",
      loc: "450 320",
    },
    {
      key: 9,
      layer: "sweetness",
      value: "lessSugar",
      text: "ขนาดเล็ก\nบราวนี่\nใส่นม",
      fill: "SaddleBrown",
      color: "white",
      loc: "700 -320",
    },
    {
      key: 10,
      layer: "sweetness",
      value: "extraSugar",
      text: "ขนาดเล็ก\nกล้วย\nใส่นม",
      fill: "SaddleBrown",
      color: "white",
      loc: "700 -200",
    },
    {
      key: 11,
      layer: "sweetness",
      value: "extraSugar",
      text: "ขนาดเล็ก\nคอนเฟรค\nใส่นม",
      fill: "SaddleBrown",
      color: "white",
      loc: "700 -80",
    },
    {
      key: 12,
      layer: "sweetness",
      value: "lessSugar",
      text: "ขนาดใหญ่\nบราวนี่\nใส่นม",
      fill: "SaddleBrown",
      color: "white",
      loc: "700 80",
    },
    {
      key: 13,
      layer: "sweetness",
      value: "extraSugar",
      text: "ขนาดใหญ่\nกล้วย\nใส่นม",
      fill: "SaddleBrown",
      color: "white",
      loc: "700 200",
    },
    {
      key: 14,
      layer: "sweetness",
      value: "extraSugar",
      text: "ขนาดเล็ก\nคอนเฟรค\nใส่นม",
      fill: "SaddleBrown",
      color: "white",
      loc: "700 320",
    },
    {
      key: 15,
      layer: "end",
      value: "end",
      fill: "black",
      color: "white",
      loc: "900 0",
      category: "End",
    },
  ],
  linkDataArray: [
    //layer 1 start -> size
    { key: -1, from: 0, to: 1, color: "green", zOrder: 2 },
    { key: -2, from: 0, to: 2, color: "#fff281", zOrder: 1 },
    //Layer 1 -> Layer 1
    { key: -3, from: 1, to: 2, color: "#fff281", zOrder: 1 },
    { key: -4, from: 2, to: 1, color: "#fff281", zOrder: 1 },
    //Layer 1 -> Layer 2
    { key: -5, from: 1, to: 3, color: "#fff281", zOrder: 1 },
    { key: -6, from: 1, to: 4, color: "#fff281", zOrder: 1 },
    { key: -7, from: 1, to: 5, color: "#fff281", zOrder: 1 },

    { key: -8, from: 2, to: 6, color: "#fff281", zOrder: 1 },
    { key: -9, from: 2, to: 7, color: "#fff281", zOrder: 1 },
    { key: -10, from: 2, to: 8, color: "#fff281", zOrder: 1 },
    //Layer 2 -> Layer 2
    { key: -11, from: 3, to: 4, color: "#fff281", zOrder: 1 },
    { key: -12, from: 3, to: 5, color: "#fff281", zOrder: 1 },

    { key: -13, from: 4, to: 3, color: "#fff281", zOrder: 1 },
    { key: -14, from: 4, to: 5, color: "#fff281", zOrder: 1 },

    { key: -15, from: 5, to: 3, color: "#fff281", zOrder: 1 },
    { key: -16, from: 5, to: 4, color: "#fff281", zOrder: 1 },

    { key: -17, from: 6, to: 7, color: "#fff281", zOrder: 1 },
    { key: -18, from: 6, to: 8, color: "#fff281", zOrder: 1 },

    { key: -19, from: 7, to: 6, color: "#fff281", zOrder: 1 },
    { key: -20, from: 7, to: 8, color: "#fff281", zOrder: 1 },

    { key: -21, from: 8, to: 6, color: "#fff281", zOrder: 1 },
    { key: -22, from: 8, to: 7, color: "#fff281", zOrder: 1 },
    //Layer 2 -> Layer 1
    { key: -23, from: 3, to: 1, color: "#fff281", zOrder: 1 },
    { key: -24, from: 4, to: 1, color: "#fff281", zOrder: 1 },
    { key: -25, from: 5, to: 1, color: "#fff281", zOrder: 1 },

    { key: -26, from: 6, to: 2, color: "#fff281", zOrder: 1 },
    { key: -27, from: 7, to: 2, color: "#fff281", zOrder: 1 },
    { key: -28, from: 8, to: 2, color: "#fff281", zOrder: 1 },
  ],
}
